### ISSUE TITLE
Git excecutable no longer found after update to 20.2.1

### ISSUE THREAD

**Issue by OzzieIsaacs** [flathub/com.syntevo.SmartGit#51] opened 2020-12-20 12:49 UTC
I'm using the flatpak smartgit since a few years, constantly updated it after the update this morning smartgit is complaining about a not found git executable (I'm using Linux Mint 20 Cinnamon).
The old path was as seen in the screenshot (I think so, I browsed so long through all the files that I lost the original one). The app folder is also not visible in the file browser which is opening. It's opening the home folder of my user.
![grafik](https://user-images.githubusercontent.com/6438895/102713481-d5099700-42c8-11eb-9696-3f507c771f89.png)
By just moving to what looks like the system `git`, I get:
![grafik](https://user-images.githubusercontent.com/6438895/102713508-1bf78c80-42c9-11eb-9eb8-98d2368d1d49.png)
![grafik](https://user-images.githubusercontent.com/6438895/102713523-2f0a5c80-42c9-11eb-89d2-26b30cd8105f.png)
The error message translated into "No permission"
I tried to change ownership of the system git version in /usr/bin/git to my "normal" login, but this didn't change anything (I think because it's somehow mapped to the flatpak package).
I guess it's related to this PR: #42

So how do I find the bundled git, or can use the system git (which I think I was using before)

Thank you for your help, and stay healthy

**Comment by x80486** [comment] 2020-12-20 15:31
I'm aware of that; initially `Git` was bundled and pointing by default to that location. I would need that @syntevo or @tmssngr rollbacks that and use an environment variable (if available), or the new bundled (by SmartGit) in `/app/extra/smartgit/git/bin/git`.

**Comment by OzzieIsaacs** [comment] 2020-12-20 15:42
Thanks, this solved my problem.

Shall we leave the issue open for others to find a solution, or shall I close it?

**Comment by x80486** [comment] 2020-12-20 18:48
Leave it open, this is something that needs to be changed since it's going to be the same for everyone else.

**Comment by RoyiAvital** [comment] 2020-12-27 00:58
The problem is using `/app/extra/smartgit/git/bin/git` means no `git-lfs` support.
Could we have something like Git in FlatPak and have it bundled with it?

**Comment by x80486** [comment] 2020-12-27 01:06
@RoyiAvital, did you test this? The current Flatpak version (`20.2.1`) have also bundled `git-lfs/2.12.0`. Can you explain what is it what doesn't work in that regard?

As a side note, the Git location business will be (or should be) fixed in the next release. **syntevo** made the changes and it is working already in a "test" build.

**Comment by RoyiAvital** [comment] 2020-12-27 09:58
This is the error I get with git configured as `/app/extra/smartgit/git/bin/git`: 

![image](https://user-images.githubusercontent.com/7347975/103168304-86b14680-483a-11eb-801d-adf9d4b15ca3.png)

This is the full text:

```
[11:53 AM] Pull (Rebase): checkout failed (return code 1)
	~/Documents/<MyProject>> git -c credential.helper=/app/extra/smartgit/lib/credentials.sh fetch --progress --prune --recurse-submodules=no origin
	/app/extra/smartgit/git/libexec/git-core/git-remote-https: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/smartgit/git/libexec/git-core/git-remote-https)
	remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0        
	From https://github.com/RoyiAvital/Projects
	   8f4d3cf..2ee86c3  master     -> origin/master
	~/Documents/MATLAB/GitHub/Projects> git -c credential.helper=/app/extra/smartgit/lib/credentials.sh checkout --quiet --ignore-other-worktrees 2ee86c37cb8eaf79d3fd0e364ffbbd1ea7e193ae
	\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n
```

As can be seen it says there is no GIT LFS support.

**Comment by x80486** [comment] 2020-12-27 14:27
OK, can you double check, if you have time, that this works with the official `.tar.gz` distribution? I tried with that one and it doesn't work either. I can go back and bundle it, but since the actual bundled Git install already have LFS support, I would guess it's some bug for now, so I will wait and see if it can be solved by SmartGit, otherwise I'll go back and install `git-lfs` as before.

**Comment by RoyiAvital** [comment] 2020-12-27 16:39
Is there a way to get @syntevo to have a look on this?

**Comment by x80486** [comment] 2020-12-27 16:55
I already wrote them via e-mail in a bug-fashion like this time. They come back super-fast most of the times, but this is not their bug tracker and also they don't support Flatpak — although based on my tests this is impacting the official release also.

**Comment by x80486** [comment] 2021-01-05 15:09
I don't know if this is a work-around or not, but setting the low-level property `executable.addBinDirectoryToPath` to `true` solves the Git LFS problem.

![image](https://user-images.githubusercontent.com/34633617/103661867-37a39980-4f3d-11eb-8aef-4adb8468b460.png)

It looks like an easy fix for the Flatpak, e.g.: adding `/app/extra/smartgit/git/bin/` to the `PATH` should be the same. I'll wait for the next release to see if it's fixed, otherwise I'll try to add it.

**Comment by RoyiAvital** [comment] 2021-01-05 15:47
@x80486 , I guess adding the path at the first place in the list will also remove the need for setting the bin folder for the git binary itself.

**Comment by RoyiAvital** [comment] 2021-01-15 14:25
I saw version `20.2.2` was released. Any chance to use it as update and fix the issue?

**Comment by x80486** [comment] 2021-01-15 14:55
The issue with the "Git executable no longer found" is fixed. The Git LFS issue is still present; I think for the time being setting `executable.addBinDirectoryToPath` to `true` is the way to go, until it's fixed upstream. I'll try adding that to the `PATH` and see what happens later — I'm on vacation mode right now.

**Closed** 2021-01-15 14:55 UTC
